services:
  app:
    build: .
    container_name: cakephp-app
    restart: always
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
